# Generated by Django 3.0.8 on 2020-07-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=26)),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField(max_length=20)),
            ],
        ),
    ]
